name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: run terraform
        working-directory: terraform
        run: 
            terraform init
      
      - name: run terraform apply
        working-directory: terraform
        run: 
            terraform apply -auto-approve


      - name: get git role credentials
        id: get_git_role
        working-directory: terraform
        run: |
            echo "GIT_ROLE_ARN=$(terraform output -raw github_actions_role_arn)" >> $GITHUB_OUTPUT
             

      - name: attach git role credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          #role-to-assume: {{ env.GIT_ROLE_ARN }}
          role-to-assume: ${{ steps.get_git_role.outputs.role_arn }}
          aws-region: us-east-2

      - name: Install Ansible and AWS dependencies
        run: |
            python3 -m pip install --upgrade pip --user
            python3 -m pip install --upgrade ansible boto3 botocore --user
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            ansible-galaxy collection install amazon.aws


      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          #ansible-playbook backend-playbook.yml -i "i-08db51b8f89469e69," -e "ansible_connection=amazon.aws.aws_ssm"
           ansible-playbook backend-playbook.yml -i hosts
