
name: Terraform and Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------
      # Checkout repo
      # ---------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Terraform
      # ----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ----------------------------
      # Terraform Init
      # ----------------------------
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # -----------------------------
      # Terraform Apply
      # -----------------------------
      - name: Terraform Apply
        working-directory: terraform
        run: 
          terraform destroy -auto-approve

      - name: Terraform output to json
        working-directory: terraform
        run: terraform output -json > tf_output.json

      # -------------------------------
      # Create inventory for Ansible
      # ----------------------------
      - name: Export Terraform outputs and build Ansible inventory
        working-directory: terraform
        run: |
          FRONTEND_IP=$(terraform output -raw frontend_ip)
          BACKEND_IP=$(terraform output -raw backend_ip)
          FRONTEND_PUBLIC_IP=$(terraform output -raw frontend_public_ip)

          echo "FRONTEND_IP=$FRONTEND_IP" >> $GITHUB_ENV
          echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV
          echo "FRONTEND_PUBLIC_IP=$FRONTEND_PUBLIC_IP" >> $GITHUB_ENV

          cat > ../ansible/inventory/hosts.ini <<EOF
          [web]
          $FRONTEND_PUBLIC_IP

          [app]
          $BACKEND_IP

          [web:vars]
          app-server-IP=$FRONTEND_IP
          EOF


      # ----------------------------
      # Install Python 
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # -----------------------------
      # Create SSH key for Ansible
      # -----------------------------
      - name: Setup SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/mykey.pem
          chmod 600 /tmp/mykey.pem

      - name: Debug inventory
        run: |
          pwd
          ls -l ansible/inventory
          cat ansible/inventory/hosts.ini
          echo "FRONTEND_IP=$FRONTEND_IP"
          echo "BACKEND_IP=$BACKEND_IP"
         

      # ----------------------------
      # Run Ansible Playbook
      # ----------------------------
      - name: Run Ansible
        working-directory: ansible
        run: |
              ansible-playbook -i inventory/hosts.ini playbook.yml -vvvvv
            

