
name: Terraform and Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------
      # Checkout repo
      # ---------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Terraform
      # ----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ----------------------------
      # Terraform Init
      # ----------------------------
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # -----------------------------
      # Terraform Apply
      # -----------------------------
      - name: Terraform Apply
        working-directory: terraform
        run: 
          terraform apply -auto-approve

      - name: Terraform output to json
        working-directory: terraform
        run: terraform output -json > tf_outputs.json

      # -------------------------------
      # Export Terraform Outputs
      # ----------------------------
      - name: Export Terraform outputs
        working-directory: terraform
        run: |
          echo "FRONTEND_IP=$(terraform output -raw frontend_ip)" >> $GITHUB_ENV
          echo "BACKEND_IP=$(terraform output -raw backend_ip)" >> $GITHUB_ENV

          cat <<EOF > ../ansible/inventory/hosts.ini
          [app]
          $FRONTEND_IP

          [web]
          $BACKEND_IP
          EOF

      # ----------------------------
      # Install Python 
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ----------------------------
      # Create SSH key for Ansible
      # ----------------------------
      - name: Setup SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem

      - name: CAT INVENTORY FILE
        working-directory: ansible
        run:
          cat inventory/hosts.ini

      - name: Debug inventory
        run: |
          pwd
          ls -l ansible/inventory
          cat ansible/inventory/hosts.ini

      # ----------------------------
      # Run Ansible Playbook
      # ----------------------------
      - name: Run Ansible
        working-directory: ansible
        run: |
              ansible-playbook -i inventory/terraform_inventory.py playbook.yml -vvvvv
            

